services:
  voxtream:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        GPU_IDS: ${GPU_IDS}
    volumes:
      - ..:/workspace
      - ${HOME}:/home/${USER}
      - ${HOME}/.cache:/root/.cache
      - ${HOME}/nltk_data:/root/nltk_data
      - ${HOME}/Documents/MFA:/root/Documents/MFA
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    shm_size: "16gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${GPU_IDS}"]
              capabilities: [gpu]
